# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='body',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Body'),
        ),
    ]
