version: '2'
services:
    db:
        image: postgres
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:80
        volumes:
            - .:/code
        ports:
            - "80:80"
        depends_on:
            - db
