version: '2'
services:
    db:
        image: postgres
    web:
        build: .
        command: tail -f /var/log/dmesg
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
