# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_answers'),
        ('uptopic', '0002_auto_20171215_2318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote_answer',
            unique_together=set([('user', 'answer')]),
        ),
    ]
