# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('uptopic', '0003_auto_20171216_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uptopic.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile')),
            ],
        ),
    ]
