# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('uptopic', '0004_topic_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic_users',
            unique_together=set([('user', 'topic')]),
        ),
    ]
